@echo off

set "KintoneSubdomain=iiglepv0966f"
set "KintoneLoginName=user01"
set "KintonePassword=abcd1234"
set "Authorization="
set "BaseUrl=https://%KintoneSubdomain%.cybozu.com"
set "ThreadId=5"
set "SpaceId=3"
set "CommentTextTemplate=アラート結果を更新しました。（{TargetGroupName} / {TargetDate}）"
set "SyncUserMasterAppId=14"
set "SyncUserMasterSheetName=受講生一覧"
set "TargetAppIds_Pulse=19"
set "TargetAppIds_Daily=17"
set "MentionUserCodes="
