@echo off

set "KintoneSubdomain=iiglepv0966f"
set "KintoneLoginName=user01"
set "KintonePassword=abcd1234"
set "Authorization="
set "BaseUrl=https://%KintoneSubdomain%.cybozu.com"
set "ThreadId=5"
set "SpaceId=3"
set "CommentTextTemplate=アラート結果を更新しました。（{TargetGroupName} / {TargetDate}）"
set "SyncUserMasterAppId=3"
set "SyncUserMasterSheetName=受講生一覧"
set "TargetAppIds_Pulse=181"
set "TargetAppIds_Daily=180"
set "MentionUserCodes=1:USER,3:USER,4:USER,fwf:USER"
