@echo off

for %%I in ("%~dp0..\..") do set "BASE_PATH=%%~fI\"

set "COMMON_LOG_PATH=%BASE_PATH%logs"
set "COMMON_CONFIG_PATH=%BASE_PATH%clients"

set "DOWNLOAD_SITE_URL="
set "DOWNLOAD_SITE_PATH="
set "DOWNLOAD_SITE_TENANT_ID="
set "DOWNLOAD_LOCAL_PATH="
set "DOWNLOAD_LOG_PREFIX=ダウンロード"

set "UPLOAD_SITE_URL="
set "UPLOAD_SITE_PATH="
set "UPLOAD_SITE_TENANT_ID="
set "UPLOAD_LOCAL_PATH="
set "UPLOAD_ITEMS_INCLUDE="
set "UPLOAD_ITEMS_EXCLUDE="
set "UPLOAD_LOG_PREFIX=アップロード"

set "GENERATE_SOURCE_PATH=%BASE_PATH%download"
set "GENERATE_CONFIG_PATH=%BASE_PATH%clients\template\package_definition.xlsx"
set "GENERATE_WORK_PATH=%BASE_PATH%work"
set "GENERATE_OUTPUT_PATH=%BASE_PATH%generated"
set "GENERATE_SHEETS_INCLUDE="
set "GENERATE_SHEETS_EXCLUDE=テンプレート"
set "GENERATE_LOG_PREFIX=パッケージ生成"
set "GENERATE_CONFIG_LOG_PREFIX=定義ファイルの更新"
