@echo off

for %%I in ("%~dp0..\..") do set "BASE_PATH=%%~fI\"

if not defined COMMON_LOG_PATH set "COMMON_LOG_PATH=%BASE_PATH%logs"
if not defined COMMON_CONFIG_PATH set "COMMON_CONFIG_PATH=%BASE_PATH%clients"

set "DOWNLOAD_SITE_URL="
set "DOWNLOAD_SITE_PATH="
set "DOWNLOAD_SITE_TENANT_ID="
set "DOWNLOAD_LOCAL_PATH="
set "UPLOAD_SITE_URL="
set "UPLOAD_SITE_PATH="
set "UPLOAD_SITE_TENANT_ID="
set "UPLOAD_LOCAL_PATH="
set "UPLOAD_ITEMS_INCLUDE="
set "UPLOAD_ITEMS_EXCLUDE="
set "GENERATE_SOURCE_PATH=%BASE_PATH%download"
set "GENERATE_CONFIG_PATH=%BASE_PATH%clients\template\package_definition.xlsx"
set "GENERATE_WORK_PATH=%BASE_PATH%work"
set "GENERATE_OUTPUT_PATH=%BASE_PATH%generated"
set "GENERATE_SHEETS_INCLUDE="
set "GENERATE_SHEETS_EXCLUDE=テンプレート"

